[package]
name = "carmine"
license = "MIT OR Apache-2.0"
authors = ["Anish Pallati <apallati@anish.land>"]
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv_codegen = "0.15.0"
poise = "0.6.1"
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
